name: azureml-book-ch5-env
channels:
  - defaults
dependencies:
  - python=3.11
  - ipykernel
  - pip
  - pip: 
    - azureml-mlflow==1.57.0.post1
    - azure-ai-ml==1.20.0
    - azure-identity==1.18.0
    - python-dotenv==1.0.1
    - mlflow==2.16.2
    - lightgbm==4.3.0
    - scikit-learn==1.4.2
    - azureml-fsspec==1.3.1
