name: azureml-book-ch8-env
channels:
  - defaults
dependencies:
  - python=3.10.4
  - pip=24.0
  - pip: 
    - azureml-mlflow==1.55.0
    - azureml-defaults==1.55.0
    - azure-ai-ml==1.15.0
    - azure-identity==1.16.0
    - python-dotenv==1.0.1
    - ipykernel==6.29.4
    - mlflow==2.12.1
    - lightgbm==4.3.0
    - scikit-learn==1.4.2
    - azureml-fsspec==1.3.1