$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: walmart-store-sales-env-inference
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
conda_file: ./conda.yaml
description: walmart-store-sales-env-inference