name: azureml-book-ch6-env
channels:
- defaults
dependencies:
- python=3.11
- ipykernel
- pip
- pip:
  - azure-ai-ml==1.20.0
  - mlflow==2.16.2
  - azureml-mlflow==1.57.0.post1
  - numpy==1.26.4
  - pandas==2.2.3
  - scikit-learn==1.4.2
  - lightgbm==4.3.0
  - interpret==0.6.1
  - kaleido==0.2.1
  - nbformat>=4.2.0